---
name: Test nornir_netmiko
on: [push, pull_request]

jobs:
  linters:
    name: linters
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v1

      - name: Install Poetry
        uses: snok/install-poetry@v1.2.0
        with:
          version: 1.1.8
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache Poetry virtualenv
        uses: actions/cache@v2
        id: cached-poetry-dependencies
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Dependencies
        run: poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

      - name: Run black
        run: |
          python -m black --check .

      - name: Run linter
        run: |
          pylama .

      - name: Run mypy
        run: |
          mypy ./nornir_netmiko/
